### ISSUE TITLE
Renaming CLI commands

### ISSUE THREAD

**Issue by abea** [apostrophecms/cli#2]
With this fresh version of the Apostrophe CLI, we have a chance to revisit the seven year old commands from the original. The legacy commands are:

- `create-project` to create a new Apos site using a boilerplate
-  `create-piece` (with `--pages` and `--widgets` options) to add a new piece type module
- `create-module` to add a generic module (extending apos-module)
- `create-widget` to add a widget module (with `--player` option to add client-side JS player)

## why change?

Primarily because these commands are repetitive and put creating a new project on the same conceptual level as adding modules. The term "create" also doesn't feel right for everything in my opinion. I also think we can make it feel lighter with a small adjustment.

Additionally, we're going to be thinking of ways to make the CLI even more useful. For example, we are considering how to add a CLI task that makes some verbose Apostrophe tasks much easier (e.g., `node app @apostrophecms/user:add name group` is a lot to remember). With that in mind, the legacy commands should feel in line with possible variety of commands to come.

## proposal

To kick things off, this is what I'm thinking

- `create` to create a new project. It's lighter and makes "create" communicate something large and new.
  - Maybe change `--boilerplate` to `--repo`? It's clearer that we're asking for a git repo.
  - With two major versions of Apostrophe in active use, The current beta version uses a `--a2` flag to use the A2 boilerplate repo. Is there a better option flag for that?
- Two possible directions for the module commands:
  - `add-module`, `add-piece`, `add-widget` for the module commands. OR
  - `add` (for generic module), `add piece`, `add widget` (so the command is `add` with the first option being a type of module. We'd add a `page` option as well later for page types. The full command would be `add helper` for a generic module called "helper" or `add piece article` for an article piece type.
- The piece command flags should go singular: `--page`, `--widget`. We're using singular more in A3. We could include aliases for the plurals as well. For A3 projects the `--widget` command wouldn't do anything since we don't have A3 piece widgets.
- The widget JS player flag... I'm not sure about this one. `--player` is okay, but it's a term you have to already know to understand it. Maybe `--browser-js` or `--js`? I'm not sure.

Please share your thoughts on this!

**Update:** To be more clear, here are a few of the proposed commands as you'd use them:
- `apos create my-project` to create an app with shortname `my-project`
- `apos add module helpers` or `apos add-module helpers` to add a generic module called `helpers`
- `apos add piece article` or `apos add-piece article` to add an `article` piece type
- `apos add widget carousel` or `apos add-widget carousel` to add a `carousel-widget-type` module (A3 naming).

**Comment by abea** [comment]
@egonzalezg9 The player file for A2 is generally `lean.js`, but could be `always.js` for the old jQuery version. In A3 the player file can be named anything. We might default to `player.js` for the CLI as a default, or use the widget type name, e.g., `slideshow.js` for `slideshow-widget-type`.

So the flag name probably wouldn't match the file name either way.

**Comment by egonzalezg9** [comment]
@abea Right, I think I still like `browser` more but `player` works too

**Comment by mtthwmnc** [comment]
generally on board with the folks above. ➕ for commands sans hyphen. feels nice to keep a consistent `add` command with the following parameter being the thing you want to add

**Comment by boutell** [comment]
Liking the general direction here.

What about piece page modules?

**Comment by abea** [comment]
> Liking the general direction here.
> 
> What about piece page modules?

Those would still be added with the `--pages` flag on `apos add piece`. Such as `apos add piece article --pages`.

**Comment by abea** [comment]
I think we're going to go ahead with the proposal using the `add widget` style for modules. Thanks everyone for your thoughts.
